#ifndef __CABLASTP_BLOSUM62_H__
#define __CABLASTP_BLOSUM62_H__

#include <stdint.h>

#define BLOSUM62_ALPHABET "ABCDEFGHIKLMNPQRSTVWXYZ"

#define BLOSUM62_SIZE 24

const int8_t BLOSUM62_RESIDUE_TO_INDEX[26];

const int BLOSUM62_MATRIX[BLOSUM62_SIZE][BLOSUM62_SIZE];

#endif
